INSERT INTO USER_SDO_GEOM_METADATA VALUES(
        'GROUPED_COLLECTOR_SUMS',
        'LONE.GET_POINT(longitude,latitude)',
        MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -140, -50, 0.0005),
        MDSYS.SDO_DIM_ELEMENT('Y', 40, 63, 0.0005)),
        8307);

INSERT INTO USER_SDO_GEOM_METADATA VALUES(
    'CN06DA',
    'GEOLOC',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', -140, -50, 0.0005),
    MDSYS.SDO_DIM_ELEMENT('Y', 40, 63, 0.0005)),
    8265);