--------------------------------------------------------
--  Fichier créé - mercredi-août-13-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence LAYER_GROUP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."LAYER_GROUP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 581 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LAYER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."LAYER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDRS_121AC$
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."MDRS_121AC$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDRS_121F8$
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."MDRS_121F8$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDRS_157F8$
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."MDRS_157F8$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17801 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MDRS_186F9$
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."MDRS_186F9$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 130101 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."SEQ_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 820 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TA_HIST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LONE"."TA_HIST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BAK_COLLECTOR
--------------------------------------------------------

  CREATE TABLE "LONE"."BAK_COLLECTOR" 
   (	"COLLECTOR_KEY" NUMBER(10,0), 
	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"DA" CHAR(8 CHAR), 
	"FSA" CHAR(3 CHAR), 
	"COORDINATE_CHANGE_DATE" DATE, 
	"ACTIVE_LAST_YEAR" NUMBER(*,0) DEFAULT 0, 
	"PROMO_MAILABLE_FLAG" NUMBER(1,0), 
	"EMAILABLE_FLAG" NUMBER(1,0), 
	"WEB_ACTIVITY_FLAG" NUMBER(1,0), 
	"MOBILE_APP_ACTIVITY_FLAG" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table BAK_POSTAL_CODE
--------------------------------------------------------

  CREATE TABLE "LONE"."BAK_POSTAL_CODE" 
   (	"POSTAL_CODE" CHAR(6 CHAR), 
	"POSTAL_CODE_CENTROID_LATITUDE" NUMBER(11,6), 
	"POSTAL_CODE_CENTROID_LONGITUDE" NUMBER(11,6), 
	"TOTAL_NUM_HHLDS" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table BAK_SPONSOR_LOCATION
--------------------------------------------------------

  CREATE TABLE "LONE"."BAK_SPONSOR_LOCATION" 
   (	"SPONSOR_KEY" NUMBER(10,0), 
	"SPONSOR_LOCATION_KEY" NUMBER(10,0), 
	"SPONSOR_CODE" CHAR(4 CHAR), 
	"SPONSOR_LOCATION_CODE" CHAR(4 CHAR), 
	"SPONSOR_LOCATION_NAME" VARCHAR2(100 CHAR), 
	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"CITY" VARCHAR2(100 CHAR), 
	"PROVINCE_CODE" CHAR(2 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"FSA" CHAR(3 CHAR), 
	"FIRST_ACTIVE" DATE, 
	"LAST_ACTIVE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table CN06DA
--------------------------------------------------------

  CREATE TABLE "LONE"."CN06DA" 
   (	"PRCDDA06" VARCHAR2(8 BYTE), 
	"AREA" NUMBER(18,2), 
	"LATITUDE" NUMBER(19,6), 
	"LONGITUDE" NUMBER(19,6), 
	"MI_PRINX" NUMBER(10,0), 
	"GEOLOC" "SDO_GEOMETRY", 
	"GEOSIMPLE" "SDO_GEOMETRY", 
	"XMIN" NUMBER(15,10), 
	"XMAX" NUMBER(15,10), 
	"YMIN" NUMBER(15,10), 
	"YMAX" NUMBER(15,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table COLLECTOR
--------------------------------------------------------

  CREATE TABLE "LONE"."COLLECTOR" 
   (	"COLLECTOR_KEY" NUMBER(10,0), 
	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"DA" CHAR(8 CHAR), 
	"FSA" CHAR(3 CHAR), 
	"COORDINATE_CHANGE_DATE" DATE, 
	"ACTIVE_LAST_YEAR" NUMBER(*,0) DEFAULT 0, 
	"PROMO_MAILABLE_FLAG" NUMBER(1,0), 
	"EMAILABLE_FLAG" NUMBER(1,0), 
	"WEB_ACTIVITY_FLAG" NUMBER(1,0), 
	"MOBILE_APP_ACTIVITY_FLAG" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table COLLECTOR_ACTIVE
--------------------------------------------------------

  CREATE TABLE "LONE"."COLLECTOR_ACTIVE" 
   (	"COLLECTOR_KEY" NUMBER(10,0), 
	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"DA" CHAR(8 CHAR), 
	"FSA" CHAR(3 CHAR), 
	"PROMO_MAILABLE_FLAG" NUMBER(1,0), 
	"EMAILABLE_FLAG" NUMBER(1,0), 
	"WEB_ACTIVITY_FLAG" NUMBER(1,0), 
	"MOBILE_APP_ACTIVITY_FLAG" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "LONE"."CUSTOMER" 
   (	"WORKSPACE" VARCHAR2(1024 CHAR), 
	"WORKSPACE_KEY" VARCHAR2(1024 BYTE), 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(4 CHAR), 
	"AMAP_ROLLUP_GROUP_NAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table FSA
--------------------------------------------------------

  CREATE TABLE "LONE"."FSA" 
   (	"FSA" VARCHAR2(3 BYTE), 
	"FSA_NAME" VARCHAR2(60 BYTE), 
	"PR" VARCHAR2(2 BYTE), 
	"MI_STYLE" VARCHAR2(254 BYTE), 
	"MI_PRINX" NUMBER(10,0), 
	"GEOLOC" "MDSYS"."SDO_GEOMETRY" 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table GROUPED_COLLECTOR_SUMS
--------------------------------------------------------

  CREATE TABLE "LONE"."GROUPED_COLLECTOR_SUMS" 
   (	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"PROMO_MAILABLE_FLAG" NUMBER, 
	"EMAILABLE_FLAG" NUMBER, 
	"WEB_ACTIVITY_FLAG" NUMBER, 
	"MOBILE_APP_ACTIVITY_FLAG" NUMBER, 
	"TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table HOTSPOT1000_AMBASE
--------------------------------------------------------

  CREATE TABLE "LONE"."HOTSPOT1000_AMBASE" 
   (	"ROUNDED_LONGITUDE" NUMBER, 
	"ROUNDED_LATITUDE" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table HOTSPOT150_AMBASE
--------------------------------------------------------

  CREATE TABLE "LONE"."HOTSPOT150_AMBASE" 
   (	"ROUNDED_LONGITUDE" NUMBER, 
	"ROUNDED_LATITUDE" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table HOTSPOT2500_AMBASE
--------------------------------------------------------

  CREATE TABLE "LONE"."HOTSPOT2500_AMBASE" 
   (	"ROUNDED_LONGITUDE" NUMBER, 
	"ROUNDED_LATITUDE" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table HOTSPOT5000_AMBASE
--------------------------------------------------------

  CREATE TABLE "LONE"."HOTSPOT5000_AMBASE" 
   (	"ROUNDED_LONGITUDE" NUMBER, 
	"ROUNDED_LATITUDE" NUMBER, 
	"COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table LAYER
--------------------------------------------------------

  CREATE TABLE "LONE"."LAYER" 
   (	"GROUP_ID" NUMBER, 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(100 CHAR), 
	"NAME" VARCHAR2(100 CHAR), 
	"LAYER_ORDER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table LAYER_GROUP
--------------------------------------------------------

  CREATE TABLE "LONE"."LAYER_GROUP" 
   (	"ID" NUMBER, 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(100 CHAR), 
	"NAME" VARCHAR2(100 CHAR), 
	"GROUP_ORDER" NUMBER(10,0), 
	"IS_OTHER" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table LOGGING
--------------------------------------------------------

  CREATE TABLE "LONE"."LOGGING" 
   (	"DATETIME" DATE, 
	"SPONSOR_KEY" NUMBER, 
	"DESCRIPTION" VARCHAR2(1024 CHAR), 
	"SPONSOR_NAME" VARCHAR2(100 CHAR), 
	"USER_NAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table MDRT_121AC$
--------------------------------------------------------

  CREATE TABLE "LONE"."MDRT_121AC$" 
   (	"NODE_ID" NUMBER, 
	"NODE_LEVEL" NUMBER, 
	"INFO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 2 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" 
 LOB ("INFO") STORE AS BASICFILE (
  TABLESPACE "LONE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table MDRT_121F8$
--------------------------------------------------------

  CREATE TABLE "LONE"."MDRT_121F8$" 
   (	"NODE_ID" NUMBER, 
	"NODE_LEVEL" NUMBER, 
	"INFO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 2 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" 
 LOB ("INFO") STORE AS BASICFILE (
  TABLESPACE "LONE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table MDRT_157F8$
--------------------------------------------------------

  CREATE TABLE "LONE"."MDRT_157F8$" 
   (	"NODE_ID" NUMBER, 
	"NODE_LEVEL" NUMBER, 
	"INFO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 2 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" 
 LOB ("INFO") STORE AS BASICFILE (
  TABLESPACE "LONE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table MDRT_186F9$
--------------------------------------------------------

  CREATE TABLE "LONE"."MDRT_186F9$" 
   (	"NODE_ID" NUMBER, 
	"NODE_LEVEL" NUMBER, 
	"INFO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 2 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" 
 LOB ("INFO") STORE AS BASICFILE (
  TABLESPACE "LONE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  MONITORING ;
--------------------------------------------------------
--  DDL for Table PDF_REPORTS
--------------------------------------------------------

  CREATE TABLE "LONE"."PDF_REPORTS" 
   (	"USER_NAME" VARCHAR2(64 BYTE), 
	"PDF_BEAN" RAW(2000), 
	"PROCESS_KEY" RAW(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table POSTAL_CODE
--------------------------------------------------------

  CREATE TABLE "LONE"."POSTAL_CODE" 
   (	"POSTAL_CODE" CHAR(6 CHAR), 
	"POSTAL_CODE_CENTROID_LATITUDE" NUMBER(11,6), 
	"POSTAL_CODE_CENTROID_LONGITUDE" NUMBER(11,6), 
	"TOTAL_NUM_HHLDS" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table PROPERTIES
--------------------------------------------------------

  CREATE TABLE "LONE"."PROPERTIES" 
   (	"NAME" VARCHAR2(64 CHAR), 
	"VALUE" VARCHAR2(1024 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "LONE"."ROLE" 
   (	"ROLE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table SPONSOR
--------------------------------------------------------

  CREATE TABLE "LONE"."SPONSOR" 
   (	"SPONSOR_KEY" NUMBER(10,0), 
	"SPONSOR_CODE" CHAR(4 CHAR), 
	"SPONSOR_NAME" VARCHAR2(100 CHAR), 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(4 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table SPONSOR_LOCATION
--------------------------------------------------------

  CREATE TABLE "LONE"."SPONSOR_LOCATION" 
   (	"SPONSOR_KEY" NUMBER(10,0), 
	"SPONSOR_LOCATION_KEY" NUMBER(10,0), 
	"SPONSOR_CODE" CHAR(4 CHAR), 
	"SPONSOR_LOCATION_CODE" CHAR(4 CHAR), 
	"SPONSOR_LOCATION_NAME" VARCHAR2(100 CHAR), 
	"LONGITUDE" NUMBER(15,10), 
	"LATITUDE" NUMBER(15,10), 
	"CITY" VARCHAR2(100 CHAR), 
	"PROVINCE_CODE" CHAR(2 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"FSA" CHAR(3 CHAR), 
	"FIRST_ACTIVE" DATE, 
	"LAST_ACTIVE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table SPONSOR_LOCATION_COLORS
--------------------------------------------------------

  CREATE TABLE "LONE"."SPONSOR_LOCATION_COLORS" 
   (	"SPONSOR_LOCATION_KEY" NUMBER(10,0), 
	"NWATCH_COLOR" VARCHAR2(21 BYTE), 
	"TA_COLOR" VARCHAR2(21 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table TA_HISTORY
--------------------------------------------------------

  CREATE TABLE "LONE"."TA_HISTORY" 
   (	"ID" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"USERNAME" VARCHAR2(100 CHAR), 
	"TYPE" VARCHAR2(60 BYTE), 
	"TYPE_DETAIL" VARCHAR2(60 BYTE), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"SPONSOR_LOCATION_KEY" NUMBER, 
	"STYLE" VARCHAR2(4000 BYTE), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" , 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table TA_TYPES
--------------------------------------------------------

  CREATE TABLE "LONE"."TA_TYPES" 
   (	"TYPE_KEY" VARCHAR2(50 BYTE), 
	"TYPE_TITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "LONE"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"LOGIN" VARCHAR2(64 CHAR), 
	"FIRSTNAME" VARCHAR2(128 CHAR), 
	"LASTNAME" VARCHAR2(128 CHAR), 
	"ROLE_ID" NUMBER(*,0), 
	"DELETED" CHAR(1 CHAR) DEFAULT 0, 
	"PASSWORD" NVARCHAR2(1024), 
	"CREATION" DATE, 
	"LAST_LOGIN_ATTEMPT" DATE, 
	"LOGIN_ATTEMPT" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Table USERS_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "LONE"."USERS_CUSTOMER" 
   (	"USER_ID" NUMBER(*,0), 
	"AMAP_ROLLUP_GROUP_CODE" VARCHAR2(4 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index SPONSOR_LOCATION_SP_KEY_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."SPONSOR_LOCATION_SP_KEY_IDX" ON "LONE"."SPONSOR_LOCATION" ("SPONSOR_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index HOTSPOT5000_AMBASE_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."HOTSPOT5000_AMBASE_IDX" ON "LONE"."HOTSPOT5000_AMBASE" ("ROUNDED_LONGITUDE", "ROUNDED_LATITUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index POSTAL_CODE_PK_PR6MP
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."POSTAL_CODE_PK_PR6MP" ON "LONE"."POSTAL_CODE" ("POSTAL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index COLLECTOR_COORDS_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."COLLECTOR_COORDS_IDX" ON "LONE"."COLLECTOR_ACTIVE" ("LONGITUDE", "LATITUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index TA_HISTORY_ROLLUP_CODE
--------------------------------------------------------

  CREATE INDEX "LONE"."TA_HISTORY_ROLLUP_CODE" ON "LONE"."TA_HISTORY" ("AMAP_ROLLUP_GROUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index COLLECTOR_FSA_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."COLLECTOR_FSA_IDX" ON "LONE"."COLLECTOR_ACTIVE" ("FSA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index COLLECTORS_KEY_I
--------------------------------------------------------

  CREATE INDEX "LONE"."COLLECTORS_KEY_I" ON "LONE"."COLLECTOR" ("COLLECTOR_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index PROPERTIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."PROPERTIES_PK" ON "LONE"."PROPERTIES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index CN06DA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."CN06DA_PK" ON "LONE"."CN06DA" ("PRCDDA06") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index PDF_REPORTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."PDF_REPORTS_PK" ON "LONE"."PDF_REPORTS" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index POSTAL_CODE_PK_C4PXF
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."POSTAL_CODE_PK_C4PXF" ON "LONE"."BAK_POSTAL_CODE" ("POSTAL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index COL_SUMS_GEOM_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."COL_SUMS_GEOM_IDX" ON "LONE"."GROUPED_COLLECTOR_SUMS" ("LONE"."GET_POINT"("LONGITUDE","LATITUDE")) 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index CN06DA_GEOM_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."CN06DA_GEOM_IDX" ON "LONE"."CN06DA" ("GEOLOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index POSTAL_CODE_COORD_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."POSTAL_CODE_COORD_IDX" ON "LONE"."POSTAL_CODE" ("LONE"."GET_POINT"("POSTAL_CODE_CENTROID_LONGITUDE","POSTAL_CODE_CENTROID_LATITUDE")) 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index COLLECTOR_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."COLLECTOR_IDX" ON "LONE"."COLLECTOR_ACTIVE" ("COLLECTOR_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."ROLE_PK" ON "LONE"."ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index HOTSPOT2500_AMBASE_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."HOTSPOT2500_AMBASE_IDX" ON "LONE"."HOTSPOT2500_AMBASE" ("ROUNDED_LONGITUDE", "ROUNDED_LATITUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index TA_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."TA_TYPES_PK" ON "LONE"."TA_TYPES" ("TYPE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index FSA_SX
--------------------------------------------------------

  CREATE INDEX "LONE"."FSA_SX" ON "LONE"."FSA" ("GEOLOC") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index GROUPED_COLLECTOR_SUMS_LOC_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."GROUPED_COLLECTOR_SUMS_LOC_IDX" ON "LONE"."GROUPED_COLLECTOR_SUMS" ("LONGITUDE", "LATITUDE", "PROMO_MAILABLE_FLAG", "EMAILABLE_FLAG", "WEB_ACTIVITY_FLAG", "MOBILE_APP_ACTIVITY_FLAG", "TOTAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index SPONSOR_LOCATION_KEY_I
--------------------------------------------------------

  CREATE INDEX "LONE"."SPONSOR_LOCATION_KEY_I" ON "LONE"."SPONSOR_LOCATION" ("SPONSOR_LOCATION_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index SPONSOR_LOCATION_SP_CODE_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."SPONSOR_LOCATION_SP_CODE_IDX" ON "LONE"."SPONSOR_LOCATION" ("SPONSOR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index HOTSPOT1000_AMBASE_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."HOTSPOT1000_AMBASE_IDX" ON "LONE"."HOTSPOT1000_AMBASE" ("ROUNDED_LONGITUDE", "ROUNDED_LATITUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index ACTIVE_COL_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."ACTIVE_COL_IDX" ON "LONE"."COLLECTOR" ("ACTIVE_LAST_YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index TA_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."TA_HISTORY_PK" ON "LONE"."TA_HISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."USERS_PK" ON "LONE"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index FSA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LONE"."FSA_PK" ON "LONE"."FSA" ("MI_PRINX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  DDL for Index HOTSPOT150_AMBASE_IDX
--------------------------------------------------------

  CREATE INDEX "LONE"."HOTSPOT150_AMBASE_IDX" ON "LONE"."HOTSPOT150_AMBASE" ("ROUNDED_LONGITUDE", "ROUNDED_LATITUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE" ;
--------------------------------------------------------
--  Constraints for Table FSA
--------------------------------------------------------

  ALTER TABLE "LONE"."FSA" ADD CONSTRAINT "FSA_PK" PRIMARY KEY ("MI_PRINX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."FSA" MODIFY ("MI_PRINX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LAYER_GROUP
--------------------------------------------------------

  ALTER TABLE "LONE"."LAYER_GROUP" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER_GROUP" MODIFY ("AMAP_ROLLUP_GROUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER_GROUP" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER_GROUP" MODIFY ("GROUP_ORDER" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER_GROUP" MODIFY ("IS_OTHER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TA_TYPES
--------------------------------------------------------

  ALTER TABLE "LONE"."TA_TYPES" MODIFY ("TYPE_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_TYPES" ADD CONSTRAINT "TA_TYPES_PK" PRIMARY KEY ("TYPE_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAYER
--------------------------------------------------------

  ALTER TABLE "LONE"."LAYER" MODIFY ("GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER" MODIFY ("AMAP_ROLLUP_GROUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."LAYER" MODIFY ("LAYER_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPONSOR_LOCATION_COLORS
--------------------------------------------------------

  ALTER TABLE "LONE"."SPONSOR_LOCATION_COLORS" MODIFY ("SPONSOR_LOCATION_KEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPONSOR
--------------------------------------------------------

  ALTER TABLE "LONE"."SPONSOR" MODIFY ("SPONSOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR" MODIFY ("SPONSOR_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR" MODIFY ("SPONSOR_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR" MODIFY ("AMAP_ROLLUP_GROUP_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "LONE"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("DELETED" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" MODIFY ("LOGIN_ATTEMPT" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "LONE"."CUSTOMER" MODIFY ("WORKSPACE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."CUSTOMER" MODIFY ("AMAP_ROLLUP_GROUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."CUSTOMER" MODIFY ("AMAP_ROLLUP_GROUP_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "LONE"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."ROLE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUPED_COLLECTOR_SUMS
--------------------------------------------------------

  ALTER TABLE "LONE"."GROUPED_COLLECTOR_SUMS" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."GROUPED_COLLECTOR_SUMS" MODIFY ("LATITUDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPONSOR_LOCATION
--------------------------------------------------------

  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("SPONSOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("SPONSOR_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("PROVINCE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."SPONSOR_LOCATION" MODIFY ("FSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLECTOR_ACTIVE
--------------------------------------------------------

  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("COLLECTOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("DA" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR_ACTIVE" MODIFY ("FSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PDF_REPORTS
--------------------------------------------------------

  ALTER TABLE "LONE"."PDF_REPORTS" ADD CONSTRAINT "PDF_REPORTS_PK" PRIMARY KEY ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."PDF_REPORTS" MODIFY ("USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAK_COLLECTOR
--------------------------------------------------------

  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("COLLECTOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("DA" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_COLLECTOR" MODIFY ("FSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CN06DA
--------------------------------------------------------

  ALTER TABLE "LONE"."CN06DA" ADD CONSTRAINT "CN06DA_PK" PRIMARY KEY ("PRCDDA06")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."CN06DA" MODIFY ("PRCDDA06" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TA_HISTORY
--------------------------------------------------------

  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("TYPE_DETAIL" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("DATE_FROM" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("DATE_TO" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" MODIFY ("STYLE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."TA_HISTORY" ADD CONSTRAINT "TA_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTAL_CODE
--------------------------------------------------------

  ALTER TABLE "LONE"."POSTAL_CODE" ADD CONSTRAINT "POSTAL_CODE_PK_PR6MP" PRIMARY KEY ("POSTAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."POSTAL_CODE" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."POSTAL_CODE" MODIFY ("POSTAL_CODE_CENTROID_LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."POSTAL_CODE" MODIFY ("POSTAL_CODE_CENTROID_LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."POSTAL_CODE" MODIFY ("TOTAL_NUM_HHLDS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "LONE"."USERS_CUSTOMER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."USERS_CUSTOMER" MODIFY ("AMAP_ROLLUP_GROUP_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAK_SPONSOR_LOCATION
--------------------------------------------------------

  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("SPONSOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("SPONSOR_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("SPONSOR_LOCATION_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("PROVINCE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_SPONSOR_LOCATION" MODIFY ("FSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BAK_POSTAL_CODE
--------------------------------------------------------

  ALTER TABLE "LONE"."BAK_POSTAL_CODE" ADD CONSTRAINT "POSTAL_CODE_PK_C4PXF" PRIMARY KEY ("POSTAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."BAK_POSTAL_CODE" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_POSTAL_CODE" MODIFY ("POSTAL_CODE_CENTROID_LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_POSTAL_CODE" MODIFY ("POSTAL_CODE_CENTROID_LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."BAK_POSTAL_CODE" MODIFY ("TOTAL_NUM_HHLDS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLECTOR
--------------------------------------------------------

  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("COLLECTOR_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("LONGITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("LATITUDE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("DA" NOT NULL ENABLE);
 
  ALTER TABLE "LONE"."COLLECTOR" MODIFY ("FSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROPERTIES
--------------------------------------------------------

  ALTER TABLE "LONE"."PROPERTIES" ADD CONSTRAINT "PROPERTIES_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LONE"  ENABLE;
 
  ALTER TABLE "LONE"."PROPERTIES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Function GET_POINT
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "LONE"."GET_POINT" (longitude IN NUMBER, latitude IN NUMBER ) RETURN mdsys.sdo_geometry DETERMINISTIC IS
  BEGIN
    RETURN mdsys.sdo_geometry (2001, 8307, mdsys.sdo_point_type (longitude, latitude, NULL), NULL, NULL );
  END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_ISNEW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "LONE"."DELETE_ISNEW" as 
begin
  null;
end delete_isnew;

/
--------------------------------------------------------
--  DDL for Procedure REFRESH_COLLECTOR_ACTIVE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "LONE"."REFRESH_COLLECTOR_ACTIVE" 
as
  i integer;
begin
    
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE COLLECTOR_ACTIVE_TMP';
    EXCEPTION
        WHEN OTHERS THEN
           IF SQLCODE != -942 THEN
                RAISE;
           END IF;
    END;
    
    EXECUTE IMMEDIATE 'create table COLLECTOR_ACTIVE_TMP as (select c.collector_key, c.longitude,
      c.latitude, c.postal_code, c.da, c.fsa,
      c.PROMO_MAILABLE_FLAG,c.EMAILABLE_FLAG,c.WEB_ACTIVITY_FLAG,c.MOBILE_APP_ACTIVITY_FLAG
    from collector c where c.active_last_year = 1)';
    commit;
    
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE COLLECTOR_ACTIVE';
    EXCEPTION
        WHEN OTHERS THEN
           IF SQLCODE != -942 THEN
                RAISE;
           END IF;
    END;
    
    EXECUTE IMMEDIATE 'ALTER TABLE COLLECTOR_ACTIVE_TMP RENAME TO COLLECTOR_ACTIVE';
    EXECUTE IMMEDIATE 'CREATE INDEX COLLECTOR_COORDS_IDX ON COLLECTOR_ACTIVE (LONGITUDE ASC, LATITUDE ASC)';
    EXECUTE IMMEDIATE 'CREATE INDEX COLLECTOR_FSA_IDX ON COLLECTOR_ACTIVE (FSA ASC)';
    --EXECUTE IMMEDIATE 'CREATE INDEX COLLECTOR_GEOM_IDX ON COLLECTOR_ACTIVE (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('' '')';
    EXECUTE IMMEDIATE 'CREATE INDEX COLLECTOR_IDX ON COLLECTOR_ACTIVE (COLLECTOR_KEY ASC)';
    -- create GROUPED_COLLECTORS_SUMS table for infotool queries
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE GROUPED_COLLECTOR_SUMS_TMP';
    EXCEPTION
        WHEN OTHERS THEN
           IF SQLCODE != -942 THEN
                RAISE;
           END IF;
    END;
    
    EXECUTE IMMEDIATE 'create table GROUPED_COLLECTOR_SUMS_TMP 
		("LONGITUDE", "LATITUDE", "PROMO_MAILABLE_FLAG", "EMAILABLE_FLAG", "WEB_ACTIVITY_FLAG", "MOBILE_APP_ACTIVITY_FLAG", "TOTAL"
		) as 
		select longitude, latitude,
		SUM(PROMO_MAILABLE_FLAG) PROMO_MAILABLE_FLAG,
		SUM(EMAILABLE_FLAG) EMAILABLE_FLAG,
		SUM(WEB_ACTIVITY_FLAG) WEB_ACTIVITY_FLAG,
		SUM(MOBILE_APP_ACTIVITY_FLAG) MOBILE_APP_ACTIVITY_FLAG,
		COUNT(*) AS total
		from collector_active group by longitude, latitude';
    commit;
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE GROUPED_COLLECTOR_SUMS';
    EXCEPTION
        WHEN OTHERS THEN
           IF SQLCODE != -942 THEN
                RAISE;
           END IF;
    END;
    
    EXECUTE IMMEDIATE 'ALTER TABLE GROUPED_COLLECTOR_SUMS_TMP RENAME TO GROUPED_COLLECTOR_SUMS';
	EXECUTE IMMEDIATE 'CREATE INDEX COL_SUMS_GEOM_IDX ON GROUPED_COLLECTOR_SUMS(GET_POINT(longitude,latitude)) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
	EXECUTE IMMEDIATE 'CREATE INDEX GROUPED_COLLECTOR_SUMS_LOC_IDX ON GROUPED_COLLECTOR_SUMS(longitude,latitude,PROMO_MAILABLE_FLAG,EMAILABLE_FLAG,WEB_ACTIVITY_FLAG,MOBILE_APP_ACTIVITY_FLAG,TOTAL)';
  commit;
end refresh_collector_active;

/
--------------------------------------------------------
--  DDL for Procedure REFRESH_HOTSPOT_AMBASE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "LONE"."REFRESH_HOTSPOT_AMBASE" 
as
  i integer;
begin
  -- refresh hotspot150_ambase
  execute immediate 'alter index hotspot150_ambase_idx unusable';  
  execute immediate 'truncate table hotspot150_ambase reuse storage';
  
  i:=0;
  for rec in (
    select    
      round(longitude * 150.0) / 150.0 as rounded_longitude,
      round(latitude * 150.0) / 150.0 as rounded_latitude,
      count(*) as count
    from collector_active
    group by 
      round(longitude * 150.0) / 150.0,
      round(latitude * 150.0) / 150.0
  )
  loop
    insert 
    into hotspot150_ambase  (rounded_longitude, rounded_latitude, count)
    values (rec.rounded_longitude, rec.rounded_latitude, rec.count);
    i:=i+1;
    if i >= 1000 then
      commit;
      i:=0;
    end if;    
  end loop;
  commit;
  
  execute immediate 'alter index hotspot150_ambase_idx rebuild';
  commit;
  
  -- refresh hotspot1000_ambase
  execute immediate 'alter index hotspot1000_ambase_idx unusable';  
  execute immediate 'truncate table hotspot1000_ambase reuse storage';
  
  i:=0;
  for rec in (
    select    
      round(longitude * 1000.0) / 1000.0 as rounded_longitude,
      round(latitude * 1000.0) / 1000.0 as rounded_latitude,
      count(*) as count
    from collector_active
    group by 
      round(longitude * 1000.0) / 1000.0,
      round(latitude * 1000.0) / 1000.0
  )
  loop
    insert 
    into hotspot1000_ambase  (rounded_longitude, rounded_latitude, count)
    values (rec.rounded_longitude, rec.rounded_latitude, rec.count);
    i:=i+1;
    if i >= 1000 then
      commit;
      i:=0;
    end if;    
  end loop;
  commit;
  
  execute immediate 'alter index hotspot1000_ambase_idx rebuild';
  commit;  
 
 -- refresh hotspot2500_ambase
 execute immediate 'alter index hotspot2500_ambase_idx unusable';  
 execute immediate 'truncate table hotspot2500_ambase reuse storage';
  
  i:=0;
  for rec in (
    select    
      round(longitude * 2500.0) / 2500.0 as rounded_longitude,
      round(latitude * 2500.0) / 2500.0 as rounded_latitude,
      count(*) as count
    from collector_active
    group by round(longitude * 2500.0) / 2500.0, round(latitude * 2500.0) / 2500.0
  )
  loop
    insert 
    into hotspot150_ambase  (rounded_longitude, rounded_latitude, count)
    values (rec.rounded_longitude, rec.rounded_latitude, rec.count);
    i:=i+1;
    if i >= 1000 then
      commit;
      i:=0;
    end if;    
  end loop;
  commit;
  
  execute immediate 'alter index hotspot2500_ambase_idx rebuild';
  commit;
 
 
 -- refresh hotspot5000_ambase
  execute immediate 'alter index hotspot5000_ambase_idx unusable';  
  execute immediate 'truncate table hotspot5000_ambase reuse storage';
  
  i:=0;
  for rec in (
    select    
      round(longitude * 5000.0) / 5000.0 as rounded_longitude,
      round(latitude * 5000.0) / 5000.0 as rounded_latitude,
      count(*) as count
    from collector_active
    group by 
      round(longitude * 5000.0) / 5000.0,
      round(latitude * 5000.0) / 5000.0
  )
  loop
    insert 
    into hotspot5000_ambase  (rounded_longitude, rounded_latitude, count)
    values (rec.rounded_longitude, rec.rounded_latitude, rec.count);
    i:=i+1;
    if i >= 1000 then
      commit;
      i:=0;
    end if;    
  end loop;
  commit;
  
  execute immediate 'alter index hotspot5000_ambase_idx rebuild';
  commit;

end REFRESH_HOTSPOT_AMBASE;

/
