
CREATE OR REPLACE PUBLIC SYNONYM "CN06DA" FOR "LONE"."CN06DA"


CREATE OR REPLACE PUBLIC SYNONYM "COLLECTOR" FOR "LONE"."COLLECTOR"


CREATE OR REPLACE PUBLIC SYNONYM "COLLECTOR_ACTIVE" FOR "LONE"."COLLECTOR_ACTIVE"


CREATE OR REPLACE PUBLIC SYNONYM "CUSTOMER" FOR "LONE"."CUSTOMER"


CREATE OR REPLACE PUBLIC SYNONYM "FSA" FOR "LONE"."FSA"


CREATE OR REPLACE PUBLIC SYNONYM "GET_POINT" FOR "LONE"."GET_POINT"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT1000_AMBASE" FOR "LONE"."HOTSPOT1000_AMBASE"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT150_AMBASE" FOR "LONE"."HOTSPOT150_AMBASE"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT2500_AMBASE" FOR "LONE"."HOTSPOT2500_AMBASE"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT5000_AMBASE" FOR "LONE"."HOTSPOT5000_AMBASE"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT5000_LOCATION" FOR "LONE"."HOTSPOT5000_LOCATION"


CREATE OR REPLACE PUBLIC SYNONYM "HOTSPOT5000_SPONSOR" FOR "LONE"."HOTSPOT5000_SPONSOR"


CREATE OR REPLACE PUBLIC SYNONYM "LOGGING" FOR "LONE"."LOGGING"


CREATE OR REPLACE PUBLIC SYNONYM "NWATCH" FOR "LONE"."NWATCH"


CREATE OR REPLACE PUBLIC SYNONYM "PROPERTIES" FOR "LONE"."PROPERTIES"


CREATE OR REPLACE PUBLIC SYNONYM "ROLE" FOR "LONE"."ROLE"


CREATE OR REPLACE PUBLIC SYNONYM "SEQ_USERS" FOR "LONE"."SEQ_USERS"


CREATE OR REPLACE PUBLIC SYNONYM "SPONSOR" FOR "LONE"."SPONSOR"


CREATE OR REPLACE PUBLIC SYNONYM "SPONSOR_LOCATION" FOR "LONE"."SPONSOR_LOCATION"


CREATE OR REPLACE PUBLIC SYNONYM "UNIVERSE" FOR "LONE"."UNIVERSE"


CREATE OR REPLACE PUBLIC SYNONYM "USERS" FOR "LONE"."USERS"


CREATE OR REPLACE PUBLIC SYNONYM "USERS_CUSTOMER" FOR "LONE"."USERS_CUSTOMER"
