  GRANT CREATE PROCEDURE TO "METRO"
  
  GRANT EXECUTE ON "LONE"."GET_POINT" TO "METRO"
 
  GRANT SELECT ON "LONE"."CN06DA" TO "METRO"
 
  GRANT SELECT ON "LONE"."HOTSPOT1000_AMBASE" TO "METRO"
 
  GRANT SELECT ON "LONE"."HOTSPOT150_AMBASE" TO "METRO"
  
  GRANT SELECT ON "LONE"."HOTSPOT2500_AMBASE" TO "METRO"
 
  GRANT SELECT ON "LONE"."HOTSPOT5000_AMBASE" TO "METRO"
 
  GRANT SELECT, UPDATE ON "LONE"."SPONSOR_LOCATION_COLORS" TO "METRO"
 
  GRANT SELECT ON "LONE"."TA_HIST_SEQ" TO "METRO"
 
  GRANT SELECT ON "LONE"."LAYER_GROUP_SEQ" TO "METRO"
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "LONE"."LAYER" TO "METRO"
 
  GRANT DELETE, INSERT, SELECT, UPDATE ON "LONE"."LAYER_GROUP" TO "METRO"
 
  GRANT SELECT ON "LONE"."BAK_COLLECTOR" TO "METRO"
 
  GRANT SELECT ON "LONE"."COLLECTOR" TO "METRO"
 
  GRANT INSERT, SELECT, UPDATE ON "LONE"."LOGGING" TO "METRO"
 
  GRANT DELETE, INSERT, SELECT ON "LONE"."TA_HISTORY" TO "METRO"
 
  GRANT SELECT ON "LONE"."POSTAL_CODE" TO "METRO"
 
  GRANT SELECT ON "LONE"."GROUPED_COLLECTOR_SUMS" TO "METRO"
 
  GRANT SELECT ON "LONE"."BAK_SPONSOR_LOCATION" TO "METRO"
 
  GRANT SELECT, UPDATE ON "LONE"."SPONSOR_LOCATION" TO "METRO"
  
  GRANT SELECT, UPDATE ON "LONE"."COLLECTOR_ACTIVE" TO "METRO"
 